name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2.1.4
      with:
        go-version: ^1.16
      id: go

    - name: Checkout code
      uses: actions/checkout@v2
      with:
          submodules: 'recursive'

    - name: Test
      run: go test ./core ./miner/... ./internal/ethapi/... ./les/...
      id: test

    - name: Build
      run: make geth-linux
      id: make

  e2e:
    name: End to End
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2.1.4
      with:
        go-version: ^1.16
      id: go

    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Checkout code
      uses: actions/checkout@v2
      with:
          submodules: 'recursive'

    - name: Build
      run: make geth-linux

    - name: Check out the e2e code repo
      uses: actions/checkout@v2.3.4
      with:
        repository: flashbots/mev-geth-demo
        path: e2e

    - run: cd e2e && yarn install
    - run: |
        cd e2e
        GETH=`pwd`/../build/bin/geth ./run.sh &
        sleep 15
        yarn run demo-simple
        yarn run demo-contract
